apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "Build and Deploy template for Quarkus applications built using a Tekton Pipeline."
    iconClass: icon-openjdk
    openshift.io/display-name: "Quarkus Fast-Jar Build & Deploy Pipeline for DEV - GitLab Webhook"
    template.openshift.io/bindable: "false"
    tags: "java,quarkus"
    version: "1.0"
  name: create-rolling-replace-quarkus-fast-jar-app
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: maven-settings-xml
    namespace: {{ .Name }}
  data:
    settings.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <settings>
          <mirrors>
              <mirror>
                  <id>${MVN_MIRROR_NAME}</id>
                  <name>${MVN_MIRROR_NAME}</name>
                  <url>https://${NEXUS_URL}/repository/${MVN_MIRROR_NAME}/</url>
                  <mirrorOf>*</mirrorOf>
              </mirror>
          </mirrors>
          <profiles>
              <profile>
                  <id>maven-nexus-repo</id>
                  <repositories>
                      <repository>
                          <id>${MVN_MIRROR_NAME}</id>
                          <name>${MVN_MIRROR_NAME}</name>
                          <url>https://${NEXUS_URL}/repository/${MVN_MIRROR_NAME}/</url>
                      </repository>
                  </repositories>
              </profile>
          </profiles>
          <activeProfiles>
              <activeProfile>maven-nexus-repo</activeProfile>
          </activeProfiles>
      </settings>
parameters:
- 
  description: "Maven Mirror Name"
  displayName: "Maven Mirror Name"
  name: MVN_MIRROR_NAME
  required: true
  value: "homelab-central"
- 
  description: "Nexus URL"
  displayName: "Nexus URL"
  name: NEXUS_URL
  required: true
  value: "nexus.my.awesome.lab:8443"
