apiVersion: v1
kind: ConfigMap
metadata:
  name: trigger-template
data:
  gitea-trigger-template.yaml: |
    apiVersion: template.openshift.io/v1
    kind: Template
    metadata:
      annotations:
        template.openshift.io/bindable: "false"
      name: gitea-tekton-trigger
    objects:
      - apiVersion: triggers.tekton.dev/v1beta1
        kind: TriggerTemplate
        metadata:
          name: ${APP_NAME}
          annotations:
            triggers.tekton.dev/old-escape-quotes: 'true'
        spec:
          params:
            - name: git-checkout-sha
              description: The git SHA to checkout
              default: main
            - name: git-repo-url
              description: The git repository url
            - name: git-signature
              description: The SHA256 signature of the payload
            - name: git-event
              description: The git event that caused the webhook to fire
            - name: trigger-payload
              description: The trigger payload
          resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                name: ${APP_NAME}-$(uid)
                labels:
                  app-name: ${APP_NAME}
              spec:
                serviceAccountName: pipeline
                pipelineRef: 
                  name: build-and-deploy-java
                params:
                - name: app-name
                  value: ${APP_NAME}
                - name: build-type
                  value: ${BUILD_TYPE}
                - name: deploy-type
                  value: ${DEPLOY_TYPE}
                - name: git-repo-url
                  value: $(tt.params.git-repo-url)
                - name: git-checkout
                  value: $(tt.params.git-checkout-sha)
                - name: clone-type
                  value: "sha"
                - name: config-git-path
                  value: "${CONFIG_PATH}"
      - apiVersion: triggers.tekton.dev/v1beta1
        kind: EventListener
        metadata:
          name: ${APP_NAME}-listener
        spec:
          serviceAccountName: pipeline
          triggers:
            - name: ${APP_NAME}-trigger
              interceptors:
                - ref:
                    apiVersion: triggers.tekton.dev
                    kind: ClusterInterceptor
                    name: "gitea"
                  params:
                  - name: "secretRef"
                    value:
                      secretName: ${APP_NAME}-githook-secret
                      secretKey: GIT_HOOK_SECRET
                  - name: "validEvents"
                    value: ["push"]
              bindings:
              - ref: ${APP_NAME}
              template:
                ref: ${APP_NAME}
    parameters:
      -
        name: APP_NAME
        required: true
      -
        name: GIT_REPOSITORY
        required: true
      -
        name: GIT_BRANCH
        required: true
        value: "main"
      - 
        name: BUILD_TYPE
        required: true
      -
        name: DEPLOY_TYPE
        required: true
        value: "rolling-replace"
      - 
        name: CONFIG_PATH
        required: true
        value: "/deploy-config"

  gitea-trigger-binding.yaml: |
    apiVersion: template.openshift.io/v1
    kind: Template
    metadata:
      annotations:
        template.openshift.io/bindable: "false"
      name: gitea-tekton-trigger-binding
    objects:
      - apiVersion: triggers.tekton.dev/v1beta1
        kind: TriggerBinding
        metadata:
          name: ${APP_NAME}
        spec:
          params:
            - name: git-checkout-sha
              value: "$(body.after)"
            - name: git-repo-url
              value: "$(body.repository.clone_url)"
    parameters:
      -
        name: APP_NAME
        required: true
