apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: validate-trigger
spec:
  params:
  - name: app-name
    type: string
    description: The application name
  - name: git-signature
    type: string
    description: The SHA256 signature of the payload
  - name: git-event
    type: string
    description: The git event that caused the webhook to fire
  - name: trigger-payload
    type: string
    description: The trigger payload
  steps:
  - name: validate
    image: image-registry.openshift-image-registry.svc:5000/openshift/java-11-builder:latest
    imagePullPolicy: IfNotPresent
    script: |
      #!/bin/bash
      cat << EOF > payload.txt
      $(params.trigger-payload)
      EOF
      cat ./payload.txt
      SIGNATURE=$(openssl dgst -sha256 -hmac "${GIT_HOOK_SECRET}" ./payload.txt)
      echo "SECRET=${GIT_HOOK_SECRET}"
      echo "COMP_SIG=${SIGNATURE}" 
      echo "VAR_SIG=$(params.git-signature)"
    env:
    - name: user.home
      value: /tekton/home
    - name: GIT_HOOK_SECRET
      valueFrom:
        secretKeyRef:
          name: "$(params.app-name)-githook-secret"
          key: GIT_HOOK_SECRET
    workingDir: "/workspace"